import{initializeApp}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";import{getAuth,onAuthStateChanged,signInWithEmailAndPassword,signOut}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";import{getFirestore,collection,getDocs,getDoc,doc,setDoc,addDoc,updateDoc,deleteDoc,query,orderBy,writeBatch}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";import{firebaseConfig}from"./firebase-config.js?v=3";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);let categories=[],products=[];
$("loginForm").onsubmit=async e=>{e.preventDefault();$("loginMessage").textContent="جارٍ تسجيل الدخول...";try{await signInWithEmailAndPassword(auth,$("email").value.trim(),$("password").value)}catch(x){$("loginMessage").textContent=errMsg(x)}};
$("logoutBtn").onclick=()=>signOut(auth);
const CLOUDINARY_CLOUD_NAME="heqkzarp",CLOUDINARY_UPLOAD_PRESET="alwajha";
async function uploadImage(file,targetId,button){
if(!file)return;
if(!file.type.startsWith("image/")){alert("يرجى اختيار صورة فقط.");return}
if(file.size>6000000){alert("حجم الصورة يجب أن يكون أقل من 6MB.");return}
const old=button.textContent;button.disabled=true;button.textContent="⏳ جاري رفع الصورة...";
try{
const form=new FormData();form.append("file",file);form.append("upload_preset",CLOUDINARY_UPLOAD_PRESET);form.append("folder","alwajha-menu");
const res=await fetch(`https://api.cloudinary.com/v1_1/${CLOUDINARY_CLOUD_NAME}/image/upload`,{method:"POST",body:form});
const data=await res.json();if(!res.ok||!data.secure_url)throw new Error(data.error?.message||"تعذر رفع الصورة.");
$(targetId).value=data.secure_url;
}catch(e){console.error(e);alert("تعذر رفع الصورة: "+e.message)}finally{button.disabled=false;button.textContent=old}
}
$("uploadHeroBtn").onclick=()=>$("heroFile").click();
$("uploadProductBtn").onclick=()=>$("productFile").click();
$("heroFile").onchange=e=>{const f=e.target.files?.[0];uploadImage(f,"heroImage",$("uploadHeroBtn"));e.target.value=""};
$("productFile").onchange=e=>{const f=e.target.files?.[0];uploadImage(f,"productImage",$("uploadProductBtn"));e.target.value=""};

onAuthStateChanged(auth,async u=>{if(!u){$("authView").classList.remove("hidden");$("appView").classList.add("hidden");return}const a=await getDoc(doc(db,"admin",u.uid));if(!a.exists()||a.data().role!=="admin"){$("loginMessage").textContent="هذا الحساب لا يملك صلاحية مدير.";await signOut(auth);return}$("authView").classList.add("hidden");$("appView").classList.remove("hidden");await loadAll()});
async function loadAll(){await Promise.all([loadSite(),loadCats(),loadProds()]);renderCats();renderProds();stats()}
async function loadSite(){const s=await getDoc(doc(db,"settings","site")),x=s.exists()?s.data():{};$("siteName").value=x.name||"الواجهة البحرية";$("siteNameEn").value=x.nameEn||"AL WAJHA AL BAHRIYA";$("siteTagline").value=x.tagline||"في الواجهة البحرية، نصنع من الطعام تجربة، ومن كل زيارة ذكرى.";$("siteTaglineEn").value=x.taglineEn||"Where every meal becomes an experience and every visit becomes a memory.";$("heroImage").value=x.heroImage||"";$("sitePhone").value=x.phone||"";$("siteInstagram").value=x.instagram||"";$("siteLocation").value=x.location||""}
async function loadCats(){const s=await getDocs(query(collection(db,"categories"),orderBy("order","asc")));categories=s.docs.map(d=>({id:d.id,...d.data()}))}
async function loadProds(){const s=await getDocs(query(collection(db,"products"),orderBy("order","asc")));products=s.docs.map(d=>({id:d.id,...d.data()}))}
function stats(){$("catCount").textContent=categories.length;$("catVisibleCount").textContent=categories.filter(x=>x.visible!==false).length;$("productCount").textContent=products.length;$("productVisibleCount").textContent=products.filter(x=>x.visible!==false).length;$("badgeNewCount").textContent=products.filter(x=>x.badge==="جديد"&&x.visible!==false).length;$("badgeSpecialCount").textContent=products.filter(x=>x.badge==="مميز"&&x.visible!==false).length;$("badgePopularCount").textContent=products.filter(x=>x.badge==="الأكثر طلبًا"&&x.visible!==false).length;$("badgePrivateCount").textContent=products.filter(x=>x.badge==="خاص"&&x.visible!==false).length}
$("saveSite").onclick=async()=>{try{await setDoc(doc(db,"settings","site"),{name:$("siteName").value.trim(),nameEn:$("siteNameEn").value.trim(),tagline:$("siteTagline").value.trim(),taglineEn:$("siteTaglineEn").value.trim(),heroImage:$("heroImage").value.trim(),phone:$("sitePhone").value.trim(),instagram:$("siteInstagram").value.trim(),location:$("siteLocation").value.trim()},{merge:true});alert("تم حفظ معلومات المطعم")}catch(e){alert(e.message)}};
$("addCategory").onclick=()=>catDialog();$("addProduct").onclick=()=>prodDialog();
function renderCats(){$("categoriesList").innerHTML=categories.map(c=>`<div class="row sortable-row ${c.visible===false?"row-hidden":""}" draggable="true" data-sort-type="cat" data-sort-id="${c.id}"><button class="drag-handle" type="button" title="اسحب للترتيب" aria-label="اسحب للترتيب">⠿</button><div class="row-main"><strong>${esc(c.name)}</strong><small>${esc(c.nameEn||"")} · ${esc(c.icon||"◈")} · الترتيب: ${c.order??0} · <span class="status">${c.visible===false?"مخفي":"ظاهر"}</span></small></div><div class="row-actions"><button class="quick-toggle ${c.visible===false?"off":""}" data-cv="${c.id}">${c.visible===false?"👁 إظهار":"◉ إخفاء"}</button><button data-e="${c.id}">تعديل</button><button class="danger" data-d="${c.id}">حذف</button></div></div>`).join("")||"<p class='message'>لا توجد أقسام بعد.</p>";document.querySelectorAll("[data-e]").forEach(b=>b.onclick=()=>catDialog(categories.find(x=>x.id===b.dataset.e)));document.querySelectorAll("[data-cv]").forEach(b=>b.onclick=()=>toggleVisibility("cat",b.dataset.cv));document.querySelectorAll("[data-d]").forEach(b=>b.onclick=()=>delCat(b.dataset.d));bindSort("cat",$("categoriesList"))}
function renderProds(){$("productsList").innerHTML=products.map(p=>{const c=categories.find(x=>x.id===p.categoryId);return`<div class="row sortable-row ${p.visible===false?"row-hidden":""}" draggable="true" data-sort-type="prod" data-sort-id="${p.id}"><button class="drag-handle" type="button" title="اسحب للترتيب" aria-label="اسحب للترتيب">⠿</button><div class="row-main"><strong>${esc(p.name)}</strong><small>${esc(p.nameEn||"")} · ${esc(c?.name||"بدون قسم")} · ${Number(p.price||0).toLocaleString("ar-SA")} ر.س · ${esc(p.badge||"بدون شارة")} · <span class="status">${p.visible===false?"مخفي":"ظاهر"}</span></small></div><div class="row-actions"><button class="quick-toggle ${p.visible===false?"off":""}" data-pv="${p.id}">${p.visible===false?"👁 إظهار":"◉ إخفاء"}</button><button class="badge-quick" data-pb="${p.id}" title="تغيير الشارة">🏷️ ${esc(p.badge||"بدون شارة")}</button><button data-pe="${p.id}">تعديل</button><button class="danger" data-pd="${p.id}">حذف</button></div></div>`}).join("")||"<p class='message'>لا توجد منتجات بعد.</p>";document.querySelectorAll("[data-pe]").forEach(b=>b.onclick=()=>prodDialog(products.find(x=>x.id===b.dataset.pe)));document.querySelectorAll("[data-pv]").forEach(b=>b.onclick=()=>toggleVisibility("prod",b.dataset.pv));document.querySelectorAll("[data-pb]").forEach(b=>b.onclick=()=>cycleBadge(b.dataset.pb));document.querySelectorAll("[data-pd]").forEach(b=>b.onclick=()=>delProd(b.dataset.pd));bindSort("prod",$("productsList"))}
async function toggleVisibility(type,id){const arr=type==="cat"?categories:products,x=arr.find(v=>v.id===id);if(!x)return;const next=x.visible===false;try{await updateDoc(doc(db,type==="cat"?"categories":"products",id),{visible:next});x.visible=next;type==="cat"?renderCats():renderProds();stats()}catch(e){alert("تعذر تغيير حالة الظهور: "+e.message)}}
async function cycleBadge(id){const p=products.find(x=>x.id===id);if(!p)return;const badges=["","جديد","مميز","الأكثر طلبًا","خاص"],i=badges.indexOf(p.badge||"");const next=badges[(i+1)%badges.length];try{await updateDoc(doc(db,"products",id),{badge:next});p.badge=next;renderProds();stats()}catch(e){alert("تعذر تغيير الشارة: "+e.message)}}
let dragState=null;
function bindSort(type,container){
 container.querySelectorAll(".sortable-row").forEach(row=>{
  row.addEventListener("dragstart",()=>{dragState={type,id:row.dataset.sortId};row.classList.add("dragging")});
  row.addEventListener("dragend",()=>{row.classList.remove("dragging");container.querySelectorAll(".drag-over").forEach(x=>x.classList.remove("drag-over"));dragState=null});
  row.addEventListener("dragover",e=>{if(!dragState||dragState.type!==type||dragState.id===row.dataset.sortId)return;e.preventDefault();row.classList.add("drag-over")});
  row.addEventListener("dragleave",()=>row.classList.remove("drag-over"));
  row.addEventListener("drop",async e=>{e.preventDefault();row.classList.remove("drag-over");if(!dragState||dragState.type!==type||dragState.id===row.dataset.sortId)return;
   const arr=type==="cat"?categories:products,from=arr.findIndex(x=>x.id===dragState.id),to=arr.findIndex(x=>x.id===row.dataset.sortId);if(from<0||to<0)return;
   const [moved]=arr.splice(from,1);arr.splice(to,0,moved);arr.forEach((x,i)=>x.order=i);
   if(type==="cat")renderCats();else renderProds();stats();
   try{const batch=writeBatch(db);arr.forEach((x,i)=>batch.update(doc(db,type==="cat"?"categories":"products",x.id),{order:i}));await batch.commit()}catch(err){alert("تعذر حفظ الترتيب: "+err.message);type==="cat"?await loadCats():await loadProds();type==="cat"?renderCats():renderProds()}
  });
 });
}
function fillSelect(v=""){$("productCategory").innerHTML=categories.map(c=>`<option value="${c.id}" ${c.id===v?"selected":""}>${esc(c.name)}</option>`).join("")}
function catDialog(c=null){$("categoryDialogTitle").textContent=c?"تعديل قسم":"إضافة قسم";$("categoryId").value=c?.id||"";$("categoryName").value=c?.name||"";$("categoryNameEn").value=c?.nameEn||"";$("categoryIcon").value=c?.icon||"◈";$("categoryOrder").value=c?.order??categories.length;$("categoryVisible").checked=c?.visible!==false;$("categoryDialog").showModal()}
$("categoryForm").onsubmit=async e=>{e.preventDefault();const id=$("categoryId").value,d={name:$("categoryName").value.trim(),nameEn:$("categoryNameEn").value.trim(),icon:$("categoryIcon").value.trim()||"◈",order:Number($("categoryOrder").value||0),visible:$("categoryVisible").checked};try{if(id)await updateDoc(doc(db,"categories",id),d);else await addDoc(collection(db,"categories"),d);$("categoryDialog").close();await loadCats();renderCats();renderProds();stats()}catch(x){alert(x.message)}};
async function delCat(id){if(products.some(p=>p.categoryId===id)){alert("لا يمكن حذف قسم يحتوي على منتجات. انقل المنتجات أولًا.");return}if(!confirm("حذف هذا القسم؟"))return;await deleteDoc(doc(db,"categories",id));await loadCats();renderCats();stats()}
function prodDialog(p=null){if(!categories.length){alert("أضف قسمًا أولًا.");return}$("productDialogTitle").textContent=p?"تعديل منتج":"إضافة منتج";$("productId").value=p?.id||"";fillSelect(p?.categoryId||categories[0].id);$("productName").value=p?.name||"";$("productNameEn").value=p?.nameEn||"";$("productPrice").value=p?.price??"";$("productDescription").value=p?.description||"";$("productDescriptionEn").value=p?.descriptionEn||"";$("productImage").value=p?.imageUrl||"";$("productBadge").value=p?.badge||"";$("productOrder").value=p?.order??products.length;$("productVisible").checked=p?.visible!==false;$("productDialog").showModal()}
$("productForm").onsubmit=async e=>{e.preventDefault();const id=$("productId").value,d={name:$("productName").value.trim(),nameEn:$("productNameEn").value.trim(),categoryId:$("productCategory").value,price:Number($("productPrice").value||0),description:$("productDescription").value.trim(),descriptionEn:$("productDescriptionEn").value.trim(),imageUrl:$("productImage").value.trim(),badge:$("productBadge").value,order:Number($("productOrder").value||0),visible:$("productVisible").checked};try{if(id)await updateDoc(doc(db,"products",id),d);else await addDoc(collection(db,"products"),d);$("productDialog").close();await loadProds();renderProds();stats()}catch(x){alert(x.message)}};
async function delProd(id){if(!confirm("حذف هذا المنتج؟"))return;await deleteDoc(doc(db,"products",id));await loadProds();renderProds();stats()}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}function errMsg(e){const map={"auth/invalid-credential":"البريد أو كلمة المرور غير صحيحة.","auth/invalid-email":"صيغة البريد الإلكتروني غير صحيحة.","auth/user-not-found":"هذا المستخدم غير موجود في Firebase Authentication.","auth/wrong-password":"كلمة المرور غير صحيحة.","auth/user-disabled":"هذا الحساب معطّل.","auth/too-many-requests":"محاولات كثيرة. حاول لاحقًا.","auth/network-request-failed":"تعذر الاتصال بـ Firebase. تحقق من الإنترنت.","auth/operation-not-allowed":"تسجيل الدخول بالبريد وكلمة المرور غير مفعّل في Firebase."};return(map[e.code]||"حدث خطأ في تسجيل الدخول: "+(e.code||"unknown"))+"\n"+(e.message||"")}

document.querySelectorAll("[data-close-dialog]").forEach(b=>b.addEventListener("click",()=>document.getElementById(b.dataset.closeDialog)?.close()));document.querySelectorAll("dialog").forEach(d=>d.addEventListener("click",e=>{if(e.target===d)d.close()}));