import{initializeApp}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";import{getAuth,onAuthStateChanged,signInWithEmailAndPassword,signOut}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";import{getFirestore,collection,getDocs,getDoc,doc,setDoc,addDoc,updateDoc,deleteDoc,query,orderBy,writeBatch,onSnapshot}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";import{firebaseConfig}from"./firebase-config.js?v=3";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);let categories=[],products=[],orders=[],ordersUnsub=null,productFilters={q:"",category:"",badge:"",visibility:""},orderFilters={q:"",status:""};
function toast(message,type="success"){const host=$("toastHost");if(!host)return;const el=document.createElement("div");el.className="toast "+(type==="error"?"toast-error":"");el.innerHTML="<span>"+(type==="error"?"⚠️":"✓")+"</span><b>"+esc(message)+"</b>";host.appendChild(el);requestAnimationFrame(()=>el.classList.add("show"));setTimeout(()=>{el.classList.remove("show");setTimeout(()=>el.remove(),220)},2600)}
function filtersActive(){return !!(productFilters.q||productFilters.category||productFilters.badge||productFilters.visibility)}function offerIsActive(p,now=new Date()){if(p.offerEnabled!==true)return false;const t=now.getTime(),start=p.offerStart?new Date(p.offerStart).getTime():-Infinity,end=p.offerEnd?new Date(p.offerEnd).getTime():Infinity;return t>=start&&t<=end&&Number(p.offerPrice)>0&&Number(p.offerPrice)<Number(p.price)}function discountPercent(p){const base=Number(p.price||0),offer=Number(p.offerPrice||0);return base>0&&offer>0&&offer<base?Math.round((1-offer/base)*100):0}function syncDiscountPreview(){const base=Number($("productBasePrice")?.value||0),offer=Number($("productOfferPrice")?.value||0);$("productDiscountPercent").value=base>0&&offer>0&&offer<base?Math.round((1-offer/base)*100)+"% خصم":""}
$("loginForm").onsubmit=async e=>{e.preventDefault();$("loginMessage").textContent="جارٍ تسجيل الدخول...";try{await signInWithEmailAndPassword(auth,$("email").value.trim(),$("password").value)}catch(x){$("loginMessage").textContent=errMsg(x)}};
$("logoutBtn").onclick=()=>signOut(auth);
const CLOUDINARY_CLOUD_NAME="heqkzarp",CLOUDINARY_UPLOAD_PRESET="alwajha";
async function uploadImage(file,targetId,button){
if(!file)return;
if(!file.type.startsWith("image/")){alert("يرجى اختيار صورة فقط.");return}
if(file.size>6000000){alert("حجم الصورة يجب أن يكون أقل من 6MB.");return}
const old=button.textContent;button.disabled=true;button.textContent="⏳ جاري رفع الصورة...";
try{
const form=new FormData();form.append("file",file);form.append("upload_preset",CLOUDINARY_UPLOAD_PRESET);form.append("folder","alwajha-menu");
const res=await fetch(`https://api.cloudinary.com/v1_1/${CLOUDINARY_CLOUD_NAME}/image/upload`,{method:"POST",body:form});
const data=await res.json();if(!res.ok||!data.secure_url)throw new Error(data.error?.message||"تعذر رفع الصورة.");
$(targetId).value=data.secure_url;
}catch(e){console.error(e);alert("تعذر رفع الصورة: "+e.message)}finally{button.disabled=false;button.textContent=old}
}
$("uploadHeroBtn").onclick=()=>$("heroFile").click();
$("uploadProductBtn").onclick=()=>$("productFile").click();
$("heroFile").onchange=e=>{const f=e.target.files?.[0];uploadImage(f,"heroImage",$("uploadHeroBtn"));e.target.value=""};
$("productFile").onchange=e=>{const f=e.target.files?.[0];uploadImage(f,"productImage",$("uploadProductBtn"));e.target.value=""};$("productPrice").oninput=()=>{$("productBasePrice").value=$("productPrice").value;syncDiscountPreview()};$("productBasePrice").oninput=syncDiscountPreview;$("productOfferPrice").oninput=syncDiscountPreview;

onAuthStateChanged(auth,async u=>{if(!u){$("authView").classList.remove("hidden");$("appView").classList.add("hidden");return}const a=await getDoc(doc(db,"admin",u.uid));if(!a.exists()||a.data().role!=="admin"){$("loginMessage").textContent="هذا الحساب لا يملك صلاحية مدير.";await signOut(auth);return}$("authView").classList.add("hidden");$("appView").classList.remove("hidden");await loadAll();startOrdersListener()});
async function loadAll(){await Promise.all([loadSite(),loadCats(),loadProds()]);renderCats();renderProds();stats()}
async function loadSite(){const s=await getDoc(doc(db,"settings","site")),x=s.exists()?s.data():{};$("siteName").value=x.name||"الواجهة البحرية";$("siteNameEn").value=x.nameEn||"AL WAJHA AL BAHRIYA";$("siteTagline").value=x.tagline||"في الواجهة البحرية، نصنع من الطعام تجربة، ومن كل زيارة ذكرى.";$("siteTaglineEn").value=x.taglineEn||"Where every meal becomes an experience and every visit becomes a memory.";$("heroImage").value=x.heroImage||"";$("sitePhone").value=x.phone||"";$("siteWhatsapp").value=x.whatsapp||"";$("siteInstagram").value=x.instagram||"";$("siteLocation").value=x.location||""}
async function loadCats(){const s=await getDocs(query(collection(db,"categories"),orderBy("order","asc")));categories=s.docs.map(d=>({id:d.id,...d.data()}))}
async function loadProds(){const s=await getDocs(query(collection(db,"products"),orderBy("order","asc")));products=s.docs.map(d=>({id:d.id,...d.data()}))}
function bindAdminTabs(){const tabs=[...document.querySelectorAll(".admin-tab")],panels=[...document.querySelectorAll(".admin-tab-panel")];const activate=name=>{tabs.forEach(b=>b.classList.toggle("active",b.dataset.tab===name));panels.forEach(p=>p.classList.toggle("active",p.dataset.panel===name));localStorage.setItem("wajha-admin-tab",name)};tabs.forEach(b=>b.onclick=()=>activate(b.dataset.tab));const saved=localStorage.getItem("wajha-admin-tab");activate(tabs.some(b=>b.dataset.tab===saved)?saved:"overview")}
function stats(){$("catCount").textContent=categories.length;$("catVisibleCount").textContent=categories.filter(x=>x.visible!==false).length;$("productCount").textContent=products.length;$("productVisibleCount").textContent=products.filter(x=>x.visible!==false).length;$("badgeNewCount").textContent=products.filter(x=>x.badge==="جديد"&&x.visible!==false).length;$("badgeSpecialCount").textContent=products.filter(x=>x.badge==="مميز"&&x.visible!==false).length;$("badgePopularCount").textContent=products.filter(x=>x.badge==="الأكثر طلبًا"&&x.visible!==false).length;$("badgePrivateCount").textContent=products.filter(x=>x.badge==="خاص"&&x.visible!==false).length}
function startOrdersListener(){if(ordersUnsub)ordersUnsub();ordersUnsub=onSnapshot(query(collection(db,"orders"),orderBy("createdAt","desc")),s=>{orders=s.docs.map(d=>({id:d.id,...d.data()}));renderOrders();updateOrderStats()},e=>{console.error("orders listener",e);$("ordersList").innerHTML='<div class="message">تعذر تحميل الطلبات. تحقق من صلاحيات Firestore.</div>';$("ordersLive").textContent="● غير متاح"})}
function orderDate(o){const v=o.createdAt;if(!v)return "بانتظار وقت الإنشاء";const d=v.toDate?v.toDate():new Date(v);return isNaN(d.getTime())?"":d.toLocaleString("ar-SA",{dateStyle:"short",timeStyle:"short"})}
function orderStatusLabel(s){return {new:"جديد",preparing:"قيد التجهيز",ready:"جاهز",completed:"مكتمل",cancelled:"ملغي"}[s]||"جديد"}
function orderStatusClass(s){return {new:"status-new",preparing:"status-preparing",ready:"status-ready",completed:"status-completed",cancelled:"status-cancelled"}[s]||"status-new"}
function filteredOrders(){const q=orderFilters.q.trim().toLowerCase();return orders.filter(o=>{const customer=o.customer||{},hay=[o.orderNumber,customer.name,customer.phone,customer.table,customer.notes].join(" ").toLowerCase();return (!q||hay.includes(q))&&(!orderFilters.status||String(o.status||"new")===orderFilters.status)})}
function renderOrders(){const w=$("ordersList");if(!w)return;const arr=filteredOrders();w.innerHTML=arr.map(o=>{const customer=o.customer||{},items=Array.isArray(o.items)?o.items:[],status=o.status||"new";return '<article class="order-card '+orderStatusClass(status)+'"><div class="order-card-head"><div><strong>'+esc(o.orderNumber||"طلب بدون رقم")+'</strong><small>'+esc(orderDate(o))+'</small></div><select class="order-status-select" data-order-status="'+o.id+'">'+['new','preparing','ready','completed','cancelled'].map(s=>'<option value="'+s+'" '+(s===status?"selected":"")+'>'+orderStatusLabel(s)+'</option>').join("")+'</select></div><div class="order-items">'+items.map((x,i)=>'<div class="order-item"><span>'+((i+1)+". "+esc(x.name||"منتج"))+' × '+Number(x.qty||1)+'</span><b>'+Number(x.total??((Number(x.price)||0)*(Number(x.qty)||1))).toLocaleString("ar-SA")+' ر.س</b></div>').join("")+'</div><div class="order-total"><span>الإجمالي</span><b>'+Number(o.total||0).toLocaleString("ar-SA")+' ر.س</b></div><div class="order-customer">'+(customer.name?'<span>👤 '+esc(customer.name)+'</span>':"")+(customer.phone?'<a href="tel:'+esc(customer.phone)+'">📞 '+esc(customer.phone)+'</a>':"")+(customer.table?'<span>🪑 طاولة '+esc(customer.table)+'</span>':"")+(customer.notes?'<span class="order-note">📝 '+esc(customer.notes)+'</span>':"")+'</div></article>'}).join("")||'<div class="message">لا توجد طلبات مطابقة.</div>';w.querySelectorAll("[data-order-status]").forEach(s=>s.onchange=()=>updateOrderStatus(s.dataset.orderStatus,s.value))}
function updateOrderStats(){const now=new Date(),today=now.toLocaleDateString("en-CA"),todayOrders=orders.filter(o=>{const v=o.createdAt;if(!v)return false;const d=v.toDate?v.toDate():new Date(v);return d.toLocaleDateString("en-CA")===today}),todayTotal=todayOrders.reduce((sum,o)=>sum+Number(o.total||0),0);$("ordersTodayCount").textContent=todayOrders.length;$("ordersTodayTotal").textContent=todayTotal.toLocaleString("ar-SA")+" ر.س";$("ordersNewCount").textContent=orders.filter(o=>(o.status||"new")==="new").length;$("ordersDoneCount").textContent=orders.filter(o=>o.status==="completed").length;$("tabOrdersCount").textContent=orders.filter(o=>(o.status||"new")==="new").length
async function updateOrderStatus(id,status){try{await updateDoc(doc(db,"orders",id),{status});toast("تم تحديث حالة الطلب")}catch(e){toast("تعذر تحديث حالة الطلب: "+e.message,"error");renderOrders()}}
function bindOrders(){$("orderSearch").oninput=e=>{orderFilters.q=e.target.value;renderOrders()};$("orderStatusFilter").onchange=e=>{orderFilters.status=e.target.value;renderOrders()};$("refreshOrders").onclick=async()=>{await loadOrdersOnce();toast("تم تحديث الطلبات")}}
async function loadOrdersOnce(){const s=await getDocs(query(collection(db,"orders"),orderBy("createdAt","desc")));orders=s.docs.map(d=>({id:d.id,...d.data()}));renderOrders();updateOrderStats()}
bindOrders();bindAdminTabs();

$("saveSite").onclick=async()=>{try{await setDoc(doc(db,"settings","site"),{name:$("siteName").value.trim(),nameEn:$("siteNameEn").value.trim(),tagline:$("siteTagline").value.trim(),taglineEn:$("siteTaglineEn").value.trim(),heroImage:$("heroImage").value.trim(),phone:$("sitePhone").value.trim(),whatsapp:$("siteWhatsapp").value.trim(),instagram:$("siteInstagram").value.trim(),location:$("siteLocation").value.trim()},{merge:true});toast("تم حفظ معلومات المطعم")}catch(e){toast(e.message,"error")}};
$("addCategory").onclick=()=>catDialog();$("addProduct").onclick=()=>prodDialog();bindProductFilters();
function renderCats(){$("categoriesList").innerHTML=categories.map(c=>`<div class="row sortable-row ${c.visible===false?"row-hidden":""}" draggable="true" data-sort-type="cat" data-sort-id="${c.id}"><button class="drag-handle" type="button" title="اسحب للترتيب" aria-label="اسحب للترتيب">⠿</button><div class="row-main"><strong>${esc(c.name)}</strong><small>${esc(c.nameEn||"")} · ${esc(c.icon||"◈")} · الترتيب: ${c.order??0} · <span class="status">${c.visible===false?"مخفي":"ظاهر"}</span></small></div><div class="row-actions"><button class="quick-toggle ${c.visible===false?"off":""}" data-cv="${c.id}">${c.visible===false?"👁 إظهار":"◉ إخفاء"}</button><button data-e="${c.id}">تعديل</button><button class="danger" data-d="${c.id}">حذف</button></div></div>`).join("")||"<p class='message'>لا توجد أقسام بعد.</p>";document.querySelectorAll("[data-e]").forEach(b=>b.onclick=()=>catDialog(categories.find(x=>x.id===b.dataset.e)));document.querySelectorAll("[data-cv]").forEach(b=>b.onclick=()=>toggleVisibility("cat",b.dataset.cv));document.querySelectorAll("[data-d]").forEach(b=>b.onclick=()=>delCat(b.dataset.d));bindSort("cat",$("categoriesList"))}
function renderProds(){fillProductFilters();const q=productFilters.q.toLowerCase(),arr=products.filter(p=>(!q||[p.name,p.nameEn].some(v=>String(v||"").toLowerCase().includes(q)))&&(!productFilters.category||p.categoryId===productFilters.category)&&(!productFilters.badge||p.badge===productFilters.badge)&&(!productFilters.visibility||(productFilters.visibility==="visible"?p.visible!==false:productFilters.visibility==="hidden"?p.visible===false:offerIsActive(p))));$("productsList").innerHTML=arr.map(p=>{const c=categories.find(x=>x.id===p.categoryId);return '<div class="row sortable-row '+(p.visible===false?"row-hidden":"")+'" draggable="'+(!filtersActive())+'" data-sort-type="prod" data-sort-id="'+p.id+'"><button class="drag-handle" type="button" title="'+(filtersActive()?"ألغِ الفلاتر أولًا للترتيب":"اسحب للترتيب")+'">⠿</button><div class="product-row-main">'+(p.imageUrl?'<button class="thumb-btn" data-preview="'+p.id+'" type="button"><img class="product-thumb" src="'+esc(p.imageUrl)+'" alt="" loading="lazy"></button>':"")+'<div class="row-main product-edit-main"><div class="inline-edit-grid"><input class="quick-name" data-qname="'+p.id+'" value="'+esc(p.name||"")+'" aria-label="اسم المنتج"><input class="quick-price" data-qprice="'+p.id+'" type="number" min="0" step="0.01" value="'+Number(p.price||0)+'" aria-label="السعر"></div><small>'+esc(p.nameEn||"")+' · '+esc(c?.name||"بدون قسم")+' · '+Number(p.price||0).toLocaleString("ar-SA")+' ر.س · '+esc(p.badge||"بدون شارة")+' · <span class="status">'+(p.visible===false?"مخفي":"ظاهر")+'</span></small></div></div><div class="row-actions"><button class="save-quick" data-qsave="'+p.id+'">💾 حفظ</button><button class="quick-toggle '+(p.visible===false?"off":"")+'" data-pv="'+p.id+'">'+(p.visible===false?"👁 إظهار":"◉ إخفاء")+'</button><button class="badge-quick" data-pb="'+p.id+'">🏷️ '+esc(p.badge||"بدون شارة")+'</button><button class="copy-btn" data-pcopy="'+p.id+'">📋 نسخ</button><button data-pe="'+p.id+'">تعديل</button><button class="danger" data-pd="'+p.id+'">حذف</button></div></div>'}).join("")||"<p class='message'>لا توجد نتائج مطابقة.</p>";document.querySelectorAll("[data-pe]").forEach(b=>b.onclick=()=>prodDialog(products.find(x=>x.id===b.dataset.pe)));document.querySelectorAll("[data-pv]").forEach(b=>b.onclick=()=>toggleVisibility("prod",b.dataset.pv));document.querySelectorAll("[data-pb]").forEach(b=>b.onclick=()=>cycleBadge(b.dataset.pb));document.querySelectorAll("[data-pcopy]").forEach(b=>b.onclick=()=>copyProduct(b.dataset.pcopy));document.querySelectorAll("[data-pd]").forEach(b=>b.onclick=()=>delProd(b.dataset.pd));document.querySelectorAll("[data-preview]").forEach(b=>b.onclick=()=>previewImage(b.dataset.preview));document.querySelectorAll("[data-qsave]").forEach(b=>b.onclick=()=>quickEditProduct(b.dataset.qsave));bindSort("prod",$("productsList"))}
async function toggleVisibility(type,id){const arr=type==="cat"?categories:products,x=arr.find(v=>v.id===id);if(!x)return;const next=x.visible===false;try{await updateDoc(doc(db,type==="cat"?"categories":"products",id),{visible:next});x.visible=next;type==="cat"?renderCats():renderProds();stats()}catch(e){toast("تعذر تغيير حالة الظهور: "+e.message,"error")}}
async function cycleBadge(id){const p=products.find(x=>x.id===id);if(!p)return;const badges=["","جديد","مميز","الأكثر طلبًا","خاص"],i=badges.indexOf(p.badge||"");const next=badges[(i+1)%badges.length];try{await updateDoc(doc(db,"products",id),{badge:next});p.badge=next;renderProds();stats()}catch(e){toast("تعذر تغيير الشارة: "+e.message,"error")}}
function fillProductFilters(){const s=$("productFilterCategory"),cur=productFilters.category;s.innerHTML='<option value="">كل الأقسام</option>'+categories.map(c=>'<option value="'+c.id+'" '+(c.id===cur?"selected":"")+'>'+esc(c.name)+'</option>').join("");$("productSearch").value=productFilters.q;$("productFilterBadge").value=productFilters.badge;$("productFilterVisibility").value=productFilters.visibility}
function bindProductFilters(){$("productSearch").oninput=e=>{productFilters.q=e.target.value;renderProds()};$("productFilterCategory").onchange=e=>{productFilters.category=e.target.value;renderProds()};$("productFilterBadge").onchange=e=>{productFilters.badge=e.target.value;renderProds()};$("productFilterVisibility").onchange=e=>{productFilters.visibility=e.target.value;renderProds()};$("clearProductFilters").onclick=()=>{productFilters={q:"",category:"",badge:"",visibility:""};renderProds()}}
async function quickEditProduct(id){const p=products.find(x=>x.id===id);if(!p)return;const name=[...document.querySelectorAll("[data-qname]")].find(x=>x.dataset.qname===id)?.value.trim();const price=Number([...document.querySelectorAll("[data-qprice]")].find(x=>x.dataset.qprice===id)?.value||0);if(!name){toast("اسم المنتج مطلوب.","error");return}try{await updateDoc(doc(db,"products",id),{name,price});p.name=name;p.price=price;renderProds();stats();toast("تم تحديث الاسم والسعر")}catch(e){toast("تعذر الحفظ: "+e.message,"error")}}
async function copyProduct(id){const p=products.find(x=>x.id===id);if(!p)return;try{const d={...p};delete d.id;d.name=(p.name||"")+" (نسخة)";d.nameEn=p.nameEn?String(p.nameEn)+" Copy":"";d.order=products.length;d.visible=false;const ref=await addDoc(collection(db,"products"),d);products.push({id:ref.id,...d});renderProds();stats();toast("تم إنشاء نسخة مخفية من المنتج")}catch(e){toast("تعذر نسخ المنتج: "+e.message,"error")}}
function previewImage(id){const p=products.find(x=>x.id===id);if(!p?.imageUrl)return;$("imagePreviewImg").src=p.imageUrl;$("imagePreviewTitle").textContent=p.name||"صورة المنتج";$("imagePreviewDialog").showModal()}
let dragState=null;
function bindSort(type,container){
 if(type==="prod"&&filtersActive()){const hint=document.querySelector("#productsList")?.previousElementSibling;if(hint)hint.textContent="🔎 الترتيب متوقف أثناء استخدام الفلاتر — امسح الفلاتر أولًا للترتيب.";return}const hint=document.querySelector("#productsList")?.previousElementSibling;if(hint)hint.textContent="↕ اسحب المنتجات لترتيب ظهورها في المنيو.";
 container.querySelectorAll(".sortable-row").forEach(row=>{
  row.addEventListener("dragstart",()=>{dragState={type,id:row.dataset.sortId};row.classList.add("dragging")});
  row.addEventListener("dragend",()=>{row.classList.remove("dragging");container.querySelectorAll(".drag-over").forEach(x=>x.classList.remove("drag-over"));dragState=null});
  row.addEventListener("dragover",e=>{if(!dragState||dragState.type!==type||dragState.id===row.dataset.sortId)return;e.preventDefault();row.classList.add("drag-over")});
  row.addEventListener("dragleave",()=>row.classList.remove("drag-over"));
  row.addEventListener("drop",async e=>{e.preventDefault();row.classList.remove("drag-over");if(!dragState||dragState.type!==type||dragState.id===row.dataset.sortId)return;
   const arr=type==="cat"?categories:products,from=arr.findIndex(x=>x.id===dragState.id),to=arr.findIndex(x=>x.id===row.dataset.sortId);if(from<0||to<0)return;
   const [moved]=arr.splice(from,1);arr.splice(to,0,moved);arr.forEach((x,i)=>x.order=i);
   if(type==="cat")renderCats();else renderProds();stats();
   try{const batch=writeBatch(db);arr.forEach((x,i)=>batch.update(doc(db,type==="cat"?"categories":"products",x.id),{order:i}));await batch.commit()}catch(err){toast("تعذر حفظ الترتيب: "+err.message,"error");type==="cat"?await loadCats():await loadProds();type==="cat"?renderCats():renderProds()}
  });
 });
}
function fillSelect(v=""){$("productCategory").innerHTML=categories.map(c=>`<option value="${c.id}" ${c.id===v?"selected":""}>${esc(c.name)}</option>`).join("")}
function catDialog(c=null){$("categoryDialogTitle").textContent=c?"تعديل قسم":"إضافة قسم";$("categoryId").value=c?.id||"";$("categoryName").value=c?.name||"";$("categoryNameEn").value=c?.nameEn||"";$("categoryIcon").value=c?.icon||"◈";$("categoryOrder").value=c?.order??categories.length;$("categoryVisible").checked=c?.visible!==false;$("categoryDialog").showModal()}
$("categoryForm").onsubmit=async e=>{e.preventDefault();const id=$("categoryId").value,d={name:$("categoryName").value.trim(),nameEn:$("categoryNameEn").value.trim(),icon:$("categoryIcon").value.trim()||"◈",order:Number($("categoryOrder").value||0),visible:$("categoryVisible").checked};try{if(id)await updateDoc(doc(db,"categories",id),d);else await addDoc(collection(db,"categories"),d);$("categoryDialog").close();await loadCats();renderCats();renderProds();stats();toast(id?"تم تحديث القسم":"تم إضافة القسم")}catch(x){alert(x.message)}};
async function delCat(id){if(products.some(p=>p.categoryId===id)){toast("لا يمكن حذف قسم يحتوي على منتجات. انقل المنتجات أولًا.","error");return}if(!confirm("حذف هذا القسم؟"))return;await deleteDoc(doc(db,"categories",id));await loadCats();renderCats();stats()}
function prodDialog(p=null){if(!categories.length){toast("أضف قسمًا أولًا.","error");return}$("productDialogTitle").textContent=p?"تعديل منتج":"إضافة منتج";$("productId").value=p?.id||"";fillSelect(p?.categoryId||categories[0].id);$("productName").value=p?.name||"";$("productNameEn").value=p?.nameEn||"";$("productPrice").value=p?.price??"";$("productOfferEnabled").value=String(p?.offerEnabled===true);$("productBasePrice").value=p?.price??"";$("productOfferPrice").value=p?.offerPrice??"";$("productOfferStart").value=p?.offerStart||"";$("productOfferEnd").value=p?.offerEnd||"";syncDiscountPreview();$("productDescription").value=p?.description||"";$("productDescriptionEn").value=p?.descriptionEn||"";$("productImage").value=p?.imageUrl||"";$("productBadge").value=p?.badge||"";$("productOrder").value=p?.order??products.length;$("productVisible").checked=p?.visible!==false;$("productDialog").showModal()}
$("productForm").onsubmit=async e=>{e.preventDefault();const id=$("productId").value,d={name:$("productName").value.trim(),nameEn:$("productNameEn").value.trim(),categoryId:$("productCategory").value,price:Number($("productBasePrice").value||$("productPrice").value||0),offerEnabled:$("productOfferEnabled").value==="true",offerPrice:Number($("productOfferPrice").value||0),offerStart:$("productOfferStart").value,offerEnd:$("productOfferEnd").value,description:$("productDescription").value.trim(),descriptionEn:$("productDescriptionEn").value.trim(),imageUrl:$("productImage").value.trim(),badge:$("productBadge").value,order:Number($("productOrder").value||0),visible:$("productVisible").checked};try{if(d.offerEnabled&&(!(d.offerPrice>0)||d.offerPrice>=d.price)){toast("سعر العرض يجب أن يكون أكبر من 0 وأقل من السعر الأساسي.","error");return}if(d.offerEnabled&&d.offerStart&&d.offerEnd&&new Date(d.offerEnd)<new Date(d.offerStart)){toast("تاريخ نهاية العرض يجب أن يكون بعد البداية.","error");return}if(id)await updateDoc(doc(db,"products",id),d);else await addDoc(collection(db,"products"),d);$("productDialog").close();await loadProds();renderProds();stats();toast(id?"تم تحديث المنتج":"تم إضافة المنتج")}catch(x){alert(x.message)}};
async function delProd(id){if(!confirm("حذف هذا المنتج؟"))return;await deleteDoc(doc(db,"products",id));await loadProds();renderProds();stats()}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}function errMsg(e){const map={"auth/invalid-credential":"البريد أو كلمة المرور غير صحيحة.","auth/invalid-email":"صيغة البريد الإلكتروني غير صحيحة.","auth/user-not-found":"هذا المستخدم غير موجود في Firebase Authentication.","auth/wrong-password":"كلمة المرور غير صحيحة.","auth/user-disabled":"هذا الحساب معطّل.","auth/too-many-requests":"محاولات كثيرة. حاول لاحقًا.","auth/network-request-failed":"تعذر الاتصال بـ Firebase. تحقق من الإنترنت.","auth/operation-not-allowed":"تسجيل الدخول بالبريد وكلمة المرور غير مفعّل في Firebase."};return(map[e.code]||"حدث خطأ في تسجيل الدخول: "+(e.code||"unknown"))+"\n"+(e.message||"")}

document.querySelectorAll("[data-close-dialog]").forEach(b=>b.addEventListener("click",()=>document.getElementById(b.dataset.closeDialog)?.close()));document.querySelectorAll("dialog").forEach(d=>d.addEventListener("click",e=>{if(e.target===d)d.close()}));