import{initializeApp}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import{getFirestore,collection,doc,query,orderBy,onSnapshot}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
import{firebaseConfig}from"./firebase-config.js?v=3";
const app=initializeApp(firebaseConfig),db=getFirestore(app),$=id=>document.getElementById(id);
const state={categories:[],products:[],active:"all",search:"",lang:"ar",site:{}};
let liveStarted=false,liveUnsubs=[];
function load(){if(liveStarted)return;liveStarted=true;applyTheme();const settingsRef=doc(db,"settings","site");
liveUnsubs.push(onSnapshot(settingsRef,s=>{state.site=s.exists()?s.data():{};applySite(state.site);setLang(state.lang)},e=>console.error("settings listener",e)));
liveUnsubs.push(onSnapshot(query(collection(db,"categories"),orderBy("order","asc")),s=>{state.categories=s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.visible!==false);renderCats();renderDrawer();renderProducts()},e=>showLiveError(e)));
liveUnsubs.push(onSnapshot(query(collection(db,"products"),orderBy("order","asc")),s=>{state.products=s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.visible!==false);renderProducts()},e=>showLiveError(e)));
setTimeout(()=>{$("loading").style.display="none"},700)}
function showLiveError(e){console.error(e);if(!state.products.length)$("emptyState").textContent="تعذر تحميل المنيو. تأكد من إعدادات Firebase."}
function applySite(s){const n=s.name||"الواجهة البحرية",ne=s.nameEn||"AL WAJHA AL BAHRIYA",tag=s.tagline||"في الواجهة البحرية، نصنع من الطعام تجربة، ومن كل زيارة ذكرى.";
$("restaurantName").textContent=n;$("restaurantNameEn").textContent=ne;$("brandMark").textContent=n;$("footerName").textContent=n;$("restaurantTagline").textContent=tag;$("footerDescription").textContent=tag;$("year").textContent=new Date().getFullYear();
const h=document.querySelector(".hero"),heroUrl=s.heroImage||"images/hero.jpg";h.style.backgroundImage=`linear-gradient(90deg,rgba(4,17,28,.94) 0%,rgba(4,17,28,.62) 43%,rgba(4,17,28,.18) 100%),linear-gradient(180deg,rgba(4,17,28,.1),rgba(4,17,28,.84)),url("${esc(optimizeImage(heroUrl,1600))}")`;h.classList.add("has-image");
if(s.phone){$("phoneLink").textContent=s.phone;$("phoneLink").href="tel:"+s.phone.replace(/\s/g,"");$("phoneLink").classList.remove("hidden")}if(s.instagram){$("instagramLink").href=s.instagram;$("instagramLink").classList.remove("hidden")}if(s.location){$("locationLink").href=s.location;$("locationLink").classList.remove("hidden")}}
function renderDrawer(){const w=$("drawerCategories");if(!w)return;w.innerHTML="";state.categories.forEach(c=>{const b=document.createElement("button");b.type="button";b.className="drawer-cat";b.innerHTML=`<span class="drawer-cat-icon">${esc(c.icon||"◈")}</span><span>${esc(state.lang==="ar"?(c.name||"قسم"):(c.nameEn||c.name||"Category"))}</span><span class="drawer-arrow">←</span>`;b.onclick=()=>{state.active=c.id;state.search="";$("menuSearch").value="";$("clearSearch").classList.add("hidden");renderCats();renderProducts();closeDrawer();$("products").scrollIntoView({behavior:"smooth",block:"start"})};w.appendChild(b)})}
function renderCats(){const w=$("categories");w.innerHTML="";const all=document.createElement("button");all.className="category-tab active";all.innerHTML='<span class="cat-icon">✦</span><span class="cat-name">'+(state.lang==="ar"?"الكل":"All")+"</span>";all.onclick=()=>{state.active="all";active(all);renderProducts()};w.appendChild(all);state.categories.forEach(c=>{const b=document.createElement("button");b.className="category-tab";b.innerHTML=`<span class="cat-icon">${esc(c.icon||"◈")}</span><span class="cat-name">${esc(state.lang==="ar"?(c.name||"قسم"):(c.nameEn||c.name||"Category"))}</span>`;b.onclick=()=>{state.active=c.id;active(b);renderProducts()};w.appendChild(b)})}
function active(b){document.querySelectorAll(".category-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active")}
function renderProducts(){const w=$("products");w.innerHTML="";let list=state.products.filter(p=>state.active==="all"||p.categoryId===state.active);const q=state.search.trim().toLowerCase();if(q)list=list.filter(p=>[p.name,p.nameEn,p.description,p.descriptionEn].concat(state.categories.filter(c=>c.id===p.categoryId).map(c=>c.name+" "+(c.nameEn||""))).join(" ").toLowerCase().includes(q));$("emptyState").classList.toggle("hidden",!!list.length);
list.forEach((p,i)=>{const name=state.lang==="ar"?(p.name||"منتج"):(p.nameEn||p.name||"Product"),desc=state.lang==="ar"?(p.description||""):(p.descriptionEn||p.description||""),badge=p.badge||"";const c=document.createElement("article");c.className="product-card";c.tabIndex=0;c.setAttribute("role","button");c.setAttribute("aria-label",state.lang==="ar"?"عرض تفاصيل "+name:"View details for "+name);c.style.setProperty("--delay",Math.min(i,8)*55+"ms");
c.innerHTML=`<div class="product-image">${p.imageUrl?`<img loading="lazy" src="${esc(optimizeImage(p.imageUrl))}" alt="${esc(name)}">`:`<div class="image-placeholder">${state.lang==="ar"?"صورة المنتج":"Product image"}</div>`}${badge?`<span class="badge ${badgeClass(badge)}">${esc(badge)}</span>`:""}</div><div class="product-body"><h3 class="product-name">${esc(name)}</h3><p class="product-en">${esc(state.lang==="ar"?(p.nameEn||""):(p.name||""))}</p><p class="product-desc">${esc(desc)}</p><div class="product-bottom"><span class="price">${Number(p.price||0).toLocaleString(state.lang==="ar"?"ar-SA":"en-US")} <span class="currency">ر.س</span></span><span class="dish-plus" aria-hidden="true">+</span></div></div>`;
c.onclick=()=>openProduct(p);c.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openProduct(p)}};w.appendChild(c)})}
function optimizeImage(url,width=900){const u=String(url||"");if(!u)return"";if(!u.includes("res.cloudinary.com/"))return u;return u.replace("/image/upload/","/image/upload/f_auto,q_auto,w_"+width+",dpr_auto/")}
function badgeClass(b){const x=String(b).toLowerCase();return x.includes("جديد")||x.includes("new")?"badge-new":x.includes("طلب")||x.includes("popular")?"badge-popular":"badge-special"}
function openDrawer(){const d=$("menuDrawer");d.classList.add("open");d.setAttribute("aria-hidden","false");document.body.classList.add("drawer-open");renderDrawer()}
function closeDrawer(){const d=$("menuDrawer");d.classList.remove("open");d.setAttribute("aria-hidden","true");document.body.classList.remove("drawer-open")}
function goSearch(){const s=$("menuSearch");$("menu").scrollIntoView({behavior:"smooth",block:"start"});setTimeout(()=>s.focus(),450)}
function applyTheme(){const saved=localStorage.getItem("wajha-theme")||"dark";document.body.classList.toggle("light-theme",saved==="light");$("themeToggle").textContent=saved==="light"?"☾":"☀";$("themeToggle").setAttribute("aria-label",saved==="light"?"الوضع الداكن":"الوضع النهاري")}
function toggleTheme(){const light=!document.body.classList.contains("light-theme");localStorage.setItem("wajha-theme",light?"light":"dark");applyTheme()}
function setLang(lang){state.lang=lang;document.documentElement.lang=lang;document.documentElement.dir=lang==="ar"?"rtl":"ltr";$("langAr").classList.toggle("active",lang==="ar");$("langEn").classList.toggle("active",lang==="en");$("restaurantName").textContent=lang==="ar"?(state.site.name||"الواجهة البحرية"):(state.site.nameEn||state.site.name||"AL WAJHA AL BAHRIYA");$("restaurantNameEn").textContent=lang==="ar"?(state.site.nameEn||"AL WAJHA AL BAHRIYA"):(state.site.name||"الواجهة البحرية");$("brandMark").textContent=lang==="ar"?(state.site.name||"الواجهة البحرية"):(state.site.nameEn||"AL WAJHA AL BAHRIYA");$("footerName").textContent=lang==="ar"?(state.site.name||"الواجهة البحرية"):(state.site.nameEn||"AL WAJHA AL BAHRIYA");$("restaurantTagline").textContent=lang==="ar"?(state.site.tagline||"في الواجهة البحرية، نصنع من الطعام تجربة، ومن كل زيارة ذكرى."):(state.site.taglineEn||"Where every meal becomes an experience and every visit becomes a memory.");$("footerDescription").textContent=$("restaurantTagline").textContent;$("heroWelcome").textContent="WELCOME TO";$("exploreButton").innerHTML=lang==="ar"?'استكشف القائمة <span>↓</span>':'Explore Menu <span>↓</span>';$("menuTitle").textContent=lang==="ar"?"قائمة الطعام":"Our Menu";$("menuDescription").textContent=lang==="ar"?"اختر قسمك واستمتع بتجربة مميزة.":"Choose a category and enjoy a special experience.";$("featuredTitle").textContent=lang==="ar"?"أطباق مميزة":"Featured Dishes";$("drawerTitle").textContent=lang==="ar"?"أقسام المنيو":"Menu Categories";$("drawerAll").textContent=lang==="ar"?"عرض كل الأصناف":"View All";$("showAll").textContent=lang==="ar"?"عرض الكل →":"View All →";$("menuSearch").placeholder=lang==="ar"?"ابحث عن طبق، مشروب أو صنف...":"Search for a dish, drink or category...";renderCats();renderProducts();renderDrawer();updateProductModalLanguage()}
$("langAr").onclick=()=>setLang("ar");$("langEn").onclick=()=>setLang("en");$("menuOpen").onclick=openDrawer;$("drawerClose").onclick=closeDrawer;$("drawerX").onclick=closeDrawer;$("drawerAll").onclick=()=>{$("showAll").click();closeDrawer()};$("heroSearch").onclick=goSearch;$("themeToggle").onclick=toggleTheme;document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeDrawer();closeProduct()}});$("menuSearch").addEventListener("input",e=>{state.search=e.target.value;$("clearSearch").classList.toggle("hidden",!state.search);renderProducts()});$("clearSearch").onclick=()=>{$("menuSearch").value="";state.search="";$("clearSearch").classList.add("hidden");renderProducts()};$("showAll").onclick=()=>{state.active="all";state.search="";$("menuSearch").value="";$("clearSearch").classList.add("hidden");renderCats();renderProducts();$("products").scrollIntoView({behavior:"smooth",block:"start"})};

function ensureProductModal(){if($("productModal"))return;const s=document.createElement("style");s.id="productModalStyles";s.textContent=`
.product-modal{position:fixed;inset:0;z-index:120;display:grid;place-items:center;padding:16px;visibility:hidden;opacity:0;pointer-events:none;transition:.28s}.product-modal.open{visibility:visible;opacity:1;pointer-events:auto}.product-modal-backdrop{position:absolute;inset:0;background:rgba(1,9,16,.78);backdrop-filter:blur(8px)}.product-modal-card{position:relative;width:min(560px,100%);max-height:min(88vh,760px);overflow:auto;background:linear-gradient(160deg,#0c2c43,#041522 72%);border:1px solid rgba(244,217,147,.28);border-radius:26px;box-shadow:0 30px 90px rgba(0,0,0,.55);transform:translateY(18px) scale(.97);transition:.32s cubic-bezier(.2,.8,.2,1)}.product-modal.open .product-modal-card{transform:none}.product-modal-image{position:relative;aspect-ratio:16/10;background:linear-gradient(135deg,#102f45,#061a2a);overflow:hidden}.product-modal-image img{width:100%;height:100%;display:block;object-fit:cover}.product-modal-image:after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,transparent 48%,rgba(3,15,24,.62))}.product-modal-close{position:absolute;top:13px;left:13px;z-index:3;width:40px;height:40px;border:1px solid rgba(255,255,255,.25);border-radius:50%;background:rgba(4,17,28,.55);backdrop-filter:blur(8px);color:#fff;font-size:25px;cursor:pointer}.product-modal-badge{position:absolute;top:15px;right:15px;z-index:3}.product-modal-body{padding:22px 22px 25px}.product-modal-kicker{font-family:"Playfair Display",serif;color:#d6ad61;letter-spacing:4px;font-size:10px;margin:0 0 6px}.product-modal-title{margin:0;color:#f7dda0;font-size:28px;font-weight:800;line-height:1.25}.product-modal-en{font-family:"Playfair Display",serif;color:#8ca0ad;font-size:12px;letter-spacing:1px;margin:5px 0 14px}.product-modal-desc{color:#b7c5cd;font-size:13px;line-height:2;margin:0 0 20px}.product-modal-footer{display:flex;align-items:center;justify-content:space-between;gap:14px;padding-top:15px;border-top:1px solid rgba(214,173,97,.15)}.product-modal-price{color:#f7d98f;font-size:22px;font-weight:800}.product-modal-currency{font-size:11px;color:#8ea0aa}.product-modal-close-text{border:1px solid rgba(214,173,97,.32);background:rgba(255,255,255,.04);color:#f4d993;border-radius:999px;padding:9px 18px;cursor:pointer}.product-card:focus-visible{outline:2px solid #f4d993;outline-offset:3px}@media(max-width:599px){.product-modal{padding:10px;align-items:end}.product-modal-card{border-radius:24px 24px 18px 18px;max-height:90vh}.product-modal-image{aspect-ratio:1/1}.product-modal-body{padding:19px 17px 21px}.product-modal-title{font-size:23px}.product-modal-desc{font-size:12px}.product-modal-price{font-size:20px}}`;document.head.appendChild(s);
const m=document.createElement("div");m.id="productModal";m.className="product-modal";m.setAttribute("aria-hidden","true");m.innerHTML='<div class="product-modal-backdrop" data-product-close></div><div class="product-modal-card" role="dialog" aria-modal="true" aria-labelledby="productModalTitle"><button type="button" class="product-modal-close" data-product-close aria-label="إغلاق">×</button><div id="productModalImage" class="product-modal-image"></div><div class="product-modal-body"><p id="productModalKicker" class="product-modal-kicker">DETAILS</p><h2 id="productModalTitle" class="product-modal-title"></h2><p id="productModalEn" class="product-modal-en"></p><p id="productModalDesc" class="product-modal-desc"></p><div class="product-modal-footer"><span id="productModalPrice" class="product-modal-price"></span><button type="button" class="product-modal-close-text" data-product-close>إغلاق</button></div></div></div>';document.body.appendChild(m);m.querySelectorAll("[data-product-close]").forEach(b=>b.addEventListener("click",closeProduct))}
let selectedProduct=null;
function openProduct(p){ensureProductModal();selectedProduct=p;const name=state.lang==="ar"?(p.name||"منتج"):(p.nameEn||p.name||"Product"),en=state.lang==="ar"?(p.nameEn||""):(p.name||""),desc=state.lang==="ar"?(p.description||"لا يوجد وصف لهذا الصنف."):(p.descriptionEn||p.description||"");const badge=p.badge||"";$("productModalKicker").textContent=state.lang==="ar"?"تفاصيل الصنف":"DISH DETAILS";$("productModalTitle").textContent=name;$("productModalEn").textContent=en;$("productModalDesc").textContent=desc;$("productModalPrice").innerHTML=Number(p.price||0).toLocaleString(state.lang==="ar"?"ar-SA":"en-US")+' <span class="product-modal-currency">ر.س</span>';const box=$("productModalImage");box.innerHTML=p.imageUrl?`<img src="${esc(optimizeImage(p.imageUrl,1100))}" alt="${esc(name)}">`:'<div class="image-placeholder">صورة المنتج</div>';if(badge){const b=document.createElement("span");b.className="badge product-modal-badge "+badgeClass(badge);b.textContent=badge;box.appendChild(b)}$("productModal").classList.add("open");$("productModal").setAttribute("aria-hidden","false");document.body.classList.add("product-modal-open");$("productModal").querySelector(".product-modal-close").focus()}
function updateProductModalLanguage(){if(selectedProduct&&$("productModal")?.classList.contains("open"))openProduct(selectedProduct)}
function closeProduct(){const m=$("productModal");if(!m)return;m.classList.remove("open");m.setAttribute("aria-hidden","true");document.body.classList.remove("product-modal-open");selectedProduct=null}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
ensureProductModal();load();