import{initializeApp}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import{getFirestore,collection,getDocs,doc,getDoc,query,orderBy}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
import{firebaseConfig}from"./firebase-config.js";
const app=initializeApp(firebaseConfig),db=getFirestore(app),$=id=>document.getElementById(id);
const state={categories:[],products:[],active:"all"};
async function load(){try{
const s=await getDoc(doc(db,"settings","site"));const site=s.exists()?s.data():{};applySite(site);
const cs=await getDocs(query(collection(db,"categories"),orderBy("order","asc")));state.categories=cs.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.visible!==false);
const ps=await getDocs(query(collection(db,"products"),orderBy("order","asc")));state.products=ps.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.visible!==false);
renderCats();renderProducts()}catch(e){console.error(e);$("emptyState").textContent="تعذر تحميل المنيو. تأكد من إعدادات Firebase."; $("emptyState").classList.remove("hidden")}finally{$("loading").style.display="none"}}
function applySite(s){const n=s.name||"الواجهة البحرية";$("restaurantName").textContent=n;$("brandMark").textContent=n;$("footerName").textContent=n;$("restaurantTagline").textContent=s.tagline||"تجربة طعام استثنائية على البحر";$("footerDescription").textContent=s.tagline||"";$("year").textContent=new Date().getFullYear();if(s.heroImage){$("restaurantName").closest(".hero").style.backgroundImage=`linear-gradient(180deg,rgba(7,24,39,.25),rgba(7,24,39,.96)),url("${s.heroImage}")`;$("restaurantName").closest(".hero").style.backgroundSize="cover";$("restaurantName").closest(".hero").style.backgroundPosition="center"}if(s.phone){$("phoneLink").textContent=s.phone;$("phoneLink").href="tel:"+s.phone.replace(/\s/g,"");$("phoneLink").classList.remove("hidden")}if(s.instagram){$("instagramLink").href=s.instagram;$("instagramLink").classList.remove("hidden")}if(s.location){$("locationLink").href=s.location;$("locationLink").classList.remove("hidden")}}
function renderCats(){const w=$("categories");w.innerHTML="";const all=document.createElement("button");all.className="category-tab active";all.textContent="الكل";all.onclick=()=>{state.active="all";active(all);renderProducts()};w.appendChild(all);state.categories.forEach(c=>{const b=document.createElement("button");b.className="category-tab";b.textContent=c.name;b.onclick=()=>{state.active=c.id;active(b);renderProducts()};w.appendChild(b)})}
function active(b){document.querySelectorAll(".category-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active")}
function renderProducts(){const w=$("products");w.innerHTML="";const list=state.products.filter(p=>state.active==="all"||p.categoryId===state.active);$("emptyState").classList.toggle("hidden",!!list.length);list.forEach(p=>{const c=document.createElement("article");c.className="product-card";c.innerHTML=`<div class="product-image">${p.imageUrl?`<img loading="lazy" src="${esc(p.imageUrl)}" alt="${esc(p.name||"")}">`:`<div class="image-placeholder">صورة المنتج</div>`}</div><div class="product-body">${p.badge?`<span class="badge">${esc(p.badge)}</span>`:""}<h3 class="product-name">${esc(p.name||"منتج")}</h3><p class="product-desc">${esc(p.description||"")}</p><div class="product-bottom"><span class="price">${Number(p.price||0).toLocaleString("ar-SA")} <span class="currency">ر.س</span></span></div></div>`;w.appendChild(c)})}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}load();